
services:
  postgres:
    image: ankane/pgvector
    container_name: pgvector_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: unified_db
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: areesha
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: backend_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env   # ✅ Load from .env only (DON’T duplicate below)
    environment:
      REDIS_URL: redis://redis:6379
      OPENAI_API_KEY: ${OPENAI_API_KEY}  # still OK to inject this

  frontend:
    build:
      context: ./frontend
    container_name: frontend_ui
    ports:
      - "5173:5173"  # Vite dev server port
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app


  adminer:
    image: adminer
    container_name: db_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:




